/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserQuotesIndexRouteImport } from './routes/user-quotes/index'
import { Route as UserQuotesCreateRouteImport } from './routes/user-quotes/create'
import { Route as UserQuotesIdEditRouteImport } from './routes/user-quotes/$id/edit'

const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserQuotesIndexRoute = UserQuotesIndexRouteImport.update({
  id: '/user-quotes/',
  path: '/user-quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserQuotesCreateRoute = UserQuotesCreateRouteImport.update({
  id: '/user-quotes/create',
  path: '/user-quotes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const UserQuotesIdEditRoute = UserQuotesIdEditRouteImport.update({
  id: '/user-quotes/$id/edit',
  path: '/user-quotes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/quotes': typeof QuotesRoute
  '/user-quotes/create': typeof UserQuotesCreateRoute
  '/user-quotes': typeof UserQuotesIndexRoute
  '/user-quotes/$id/edit': typeof UserQuotesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/quotes': typeof QuotesRoute
  '/user-quotes/create': typeof UserQuotesCreateRoute
  '/user-quotes': typeof UserQuotesIndexRoute
  '/user-quotes/$id/edit': typeof UserQuotesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/posts': typeof PostsRoute
  '/quotes': typeof QuotesRoute
  '/user-quotes/create': typeof UserQuotesCreateRoute
  '/user-quotes/': typeof UserQuotesIndexRoute
  '/user-quotes/$id/edit': typeof UserQuotesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/login'
    | '/posts'
    | '/quotes'
    | '/user-quotes/create'
    | '/user-quotes'
    | '/user-quotes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/posts'
    | '/quotes'
    | '/user-quotes/create'
    | '/user-quotes'
    | '/user-quotes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/login'
    | '/posts'
    | '/quotes'
    | '/user-quotes/create'
    | '/user-quotes/'
    | '/user-quotes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  PostsRoute: typeof PostsRoute
  QuotesRoute: typeof QuotesRoute
  UserQuotesCreateRoute: typeof UserQuotesCreateRoute
  UserQuotesIndexRoute: typeof UserQuotesIndexRoute
  UserQuotesIdEditRoute: typeof UserQuotesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-quotes/': {
      id: '/user-quotes/'
      path: '/user-quotes'
      fullPath: '/user-quotes'
      preLoaderRoute: typeof UserQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-quotes/create': {
      id: '/user-quotes/create'
      path: '/user-quotes/create'
      fullPath: '/user-quotes/create'
      preLoaderRoute: typeof UserQuotesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-quotes/$id/edit': {
      id: '/user-quotes/$id/edit'
      path: '/user-quotes/$id/edit'
      fullPath: '/user-quotes/$id/edit'
      preLoaderRoute: typeof UserQuotesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  PostsRoute: PostsRoute,
  QuotesRoute: QuotesRoute,
  UserQuotesCreateRoute: UserQuotesCreateRoute,
  UserQuotesIndexRoute: UserQuotesIndexRoute,
  UserQuotesIdEditRoute: UserQuotesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
